# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: 'Rules'
  link: '/rules'
- label: Guides
  items:
    - label: 'Join a Town'
      link: '/guides/joining-a-town'
    - label: 'Protect Your Things'
      link: '/guides/protect-your-things'
    - label: 'Managing a Town'
      link: '/guides/managing-a-town'
    - label: 'Managing a Nation'
      link: '/guides/managing-a-nation'
    - label: 'War'
      link: '/guides/war'
    - label: 'Economy'
      link: '/guides/economy'
    - label: 'Quests'
      link: '/guides/quests'
    - label: 'Dungeons'
      link: '/guides/dungeons'
    - label: 'Creating a Shop'
      link: '/guides/creating-a-shop'
    - label: 'DragonSlayer'
      link: '/guides/dragonslayer'
    - label: 'Voting'
      link: '/guides/voting'
    - label: 'Brewery'
      link: '/guides/brewery'
    - label: 'mcMMO'
      link: '/guides/mcmmo'
    - label: 'Pets'
      link: '/guides/my-pet'
    - label: 'Miscellaneous'
      link: '/guides/miscellaneous'

- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'World Map'
      link: https://map.gods-sandbox.com
    - label: 'Store'
      link: https://map.gods-sandbox.com
